---
- name: "Enable the mandatory scap policies"
  include_tasks: ensure_scap_policy.yml
  loop: "{{ scap_policies_mandatory }}"
  loop_control:
    loop_var: tailoring
  when: scap_policies_mandatory is defined