---
# This playbook configures the mandatory product repo sync plans
#
- name: Create the mandatory synchronization plans 
  include_tasks: create_sync_plan.yml
  loop: "{{ sync_plans_mandatory }}"
  loop_control:
    loop_var: sp
  when: "sync_plans_mandatory is defined"

