---
# Mandatory parameters ensure lab usecases behave appropriately
# Optional parameters can be added for your usecases
- name: "Configuring the mandatory global parameters"
  include_tasks: ensure_global_parameter.yml
  loop: "{{ global_parameters_optional }}"
  loop_control:
    loop_var: gp
  when: global_parameters_optional is defined