---
- name: "Create the activation key"
  redhat.satellite.activation_key:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    organization: "{{ ak.organization }}"
    validate_certs: "{{ satellite_validate_certs }}"
    state: "present"
    name: "{{ ak.name }}"
    description: "{{ ak.description | default(omit) }}"
    lifecycle_environment: "{{ ak.lifecycle_environment }}"
    content_view: "{{ ak.content_view }}"
    content_overrides: "{{ ak.content_overrides | default(omit) }}"
    auto_attach: "{{ ak.auto_attach | default(omit) }}"
    subscriptions: "{{ ak.subscriptions | default(omit) }}"
    max_hosts: "{{ ak.max_hosts | default(omit) }}"
    unlimited_hosts: "{{ ak.unlimited_hosts | default(omit) }}"
    purpose_role: "{{ ak.purpose_role | default(omit) }}"
    purpose_usage: "{{ ak.purpose_usage | default(omit) }}"
    release_version: "{{ ak.release_version | default(omit) }}"
    service_level: "{{ ak.service_level | default(omit) }}"
    host_collections: "{{ ak.host_collections | default(omit) }}"
