- name: "Create the compute resource"
  redhat.satellite.compute_resource:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    name: "{{ cr.name }}"
    locations: "{{ cr.locations }}"
    organizations: "{{ cr.organizations }}"
    provider: "{{ cr.provider }}"
    provider_params: "{{ cr.provider_params }}"
    state: present

- name: "Create compute resource images"
  redhat.satellite.image:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_validate_certs }}"
    name: "{{ item.name }}"
    architecture: "{{ item.architecture | default('x86_64') }}"
    compute_resource: "{{ cr.name }}"
    image_password: "{{ item.image_password | default(omit) }}"
    image_username: "{{ item.image_username | default(omit) }}"
    operatingsystem: "{{ item.operatingsystem | default(omit) }}"
    user_data: "{{ item.user_data | default(omit) }}"
    uuid: "{{ item.uuid | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ cr.images | default([]) }}"
