---
- name: "Add disk to the vm - powered off"
  community.vmware.vmware_guest_disk:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ guest_fqdn }}"
    disk:
      - size_mb: "{{ disk_size_mb }}"
        scsi_controller: "{{ scsi_controller }}"
        unit_number: "{{ unit_number }}"
        type: "{{ type }}"
        scsi_type: "{{ scsi_type }}"
        disk_mode: "{{ disk_mode }}"
        state: "present"
    validate_certs: false
  delegate_to: localhost
  tags:
    - build
