---
- name: "Create the vm - powered off"
  community.vmware.vmware_guest:
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    annotation: "Build for labbuilder"
    cluster: "{{ vcenter_cluster }}"
    datacenter: "{{ vcenter_datacenter }}"
    datastore: "{{ vcenter_datastore }}"
    folder: "/{{ vcenter_datacenter }}/vm"
    hostname: "{{ vcenter_hostname }}"
    name: "{{ guest_fqdn }}"
    guest_id: "rhel8_64Guest"
    advanced_settings:
      - key: "guestinfo.metadata"
        value: "{{ guest_cloud_init_metadata }}"
      - key: "guestinfo.metadata.encoding"
        value: "gzip+base64"
      - key: "guestinfo.userdata"
        value: "{{ guest_cloud_init_userdata }}"
      - key: "guestinfo.userdata.encoding"
        value: "gzip+base64"
    hardware:
      hotadd_cpu: "{{ guest_hot_cpu_add }}"
      hotadd_memory: "{{ guest_hot_memory_add }}"
      memory_mb: "{{ guest_memory_mb }}"
      num_cpu_cores_per_socket: "{{ guest_cpu_cores_per_socket }}"
      num_cpus: "{{ guest_cpu_sockets }}"
    networks:
      - name: "{{ vcenter_network }}"
        connected: true
        gateway: "{{ guest_gateway }}"
        netmask: "{{ guest_netmask }}"
        ip: "{{ guest_ip }}"
        start_connected: true
        device_type: "{{ guest_network_device_type }}"
        type: "{{ guest_network_config_type }}"
    state: "powered-off"
    validate_certs: false
  delegate_to: localhost
  tags:
    - build

# if the file extension is not vmdk, govc will not properly convert the image automagically
- name: "Copy the image to the folder for guest"
  ansible.builtin.shell: |
    export GOVC_USERNAME={{ vcenter_username }}
    export GOVC_PASSWORD={{ vcenter_password }}
    export GOVC_DATACENTER={{ vcenter_datacenter }}
    export GOVC_INSECURE={{ vcenter_skip_certs }}
    export GOVC_DATASTORE={{ vcenter_datastore }}
    export GOVC_URL=https://{{ vcenter_hostname }}
    govc datastore.cp {{ vcenter_base_folder_path }}/{{ image_file_name }} {{ guest_fqdn }}/{{ builder_image_name}}.{{ image_extension }}
  delegate_to: localhost
  tags:
    - build

- name: "Add disk to the vm - powered off"
  community.vmware.vmware_guest_disk:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ guest_fqdn }}"
    disk:
      - scsi_controller: 0
        unit_number: 0
        scsi_type: "paravirtual"
        filename: "[{{ vcenter_datastore }}] {{ guest_fqdn }}/{{ builder_image_name}}.{{ image_extension }}"
        size_gb: "{{ guest_rootdisk_size_gb }}"
    validate_certs: false
  delegate_to: localhost
  tags:
    - build

- name: "Power on the vm"
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    name: "{{ guest_fqdn }}"
    state: "powered-on"
  delegate_to: localhost
  register: deploy
  tags:
    - build

- name: "Wait for system to allow ssh"
  ansible.builtin.wait_for:
    port: 22
    host: "{{ guest_fqdn }}"
    search_regex: OpenSSH
    sleep: 5
    delay: 180
  tags:
    - build
