---
- name: "Create the idm primary server"
  ansible.builtin.include_tasks: create_guest_from_image.yml
  vars:
    guest_ip: "{{ idm_ip }}"
    guest_fqdn: "{{ idm_fqdn }}"
    guest_gateway: "{{ build_gateway }}"
    guest_netmask: "{{ build_netmask }}"
    guest_cloud_init_metadata: "{{ idm_cloud_init_metadata }}"
    guest_cloud_init_userdata: "{{ idm_cloud_init_userdata }}"
    guest_cpu_cores_per_socket: "{{idm_cpu_cores_per_socket }}"
    guest_cpu_sockets: "{{ idm_cpu_sockets }}"
    guest_memory_mb: "{{ idm_memory_mb }}"
    guest_network_device_type: "{{ idm_network_device_type }}"
    guest_network_config_type: "{{ idm_network_config_type }}"
    guest_hot_cpu_add: "{{ idm_hot_cpu_add }}"
    guest_hot_memory_add: "{{ idm_hot_memory_add }}"
    guest_rootdisk_size_gb: "{{ idm_rootdisk_size_gb }}"
