---
- name: "Create the satellite primary server"
  ansible.builtin.include_tasks: create_guest_from_image.yml
  vars:
    guest_ip: "{{ sat_ip }}"
    guest_fqdn: "{{ sat_fqdn }}"
    guest_gateway: "{{ build_gateway }}"
    guest_netmask: "{{ build_netmask }}"
    guest_cloud_init_metadata: "{{ sat_cloud_init_metadata }}"
    guest_cloud_init_userdata: "{{ sat_cloud_init_userdata }}"
    guest_cpu_cores_per_socket: "{{ sat_cpu_cores_per_socket }}"
    guest_cpu_sockets: "{{ sat_cpu_sockets }}"
    guest_memory_mb: "{{ sat_memory_mb }}"
    guest_network_device_type: "{{ sat_network_device_type }}"
    guest_network_config_type: "{{ sat_network_config_type }}"
    guest_hot_cpu_add: "{{ sat_hot_cpu_add }}"
    guest_hot_memory_add: "{{ sat_hot_memory_add }}"
    guest_rootdisk_size_gb: "{{ sat_rootdisk_size_gb }}"
  tags:
    - build_satellite_primary

- name: "Add data disk to the satellite primary server"
  ansible.builtin.include_tasks: add_disk_to_guest.yml
  vars:
    guest_ip: "{{ sat_ip }}"
    guest_fqdn: "{{ sat_fqdn }}"
    disk_size_mb: "{{ sat_data_disk_size_mb }}"
    scsi_controller: "{{ sat_data_disk_scsi_controller }}"
    unit_number: "{{ sat_data_disk_unit_number }}"
    type: "{{ sat_data_disk_type }}"
    scsi_type: "{{ sat_data_disk_scsi_type }}"
    disk_mode: "{{ sat_data_disk_disk_mode }}"
  tags:
    - build_satellite_primary
  
- name: "Reconfigure Satellite storage volumes"
  ansible.builtin.include_tasks: ensure_image_storage_config.yml
  vars:
    guest_fqdn: "{{ sat_fqdn }}"
    pv_list: "{{ sat_pv_list }}"
  tags:
    - build_satellite_primary
  