---
- name: "buildimage"
  hosts: build_control
  remote_user: ansiblerunner
  become: true
  gather_facts: true
  vars_files:
    - vars/builder_vars.yml
    - vars/builder_vault.yml
    - vars/vmware_vars.yml
    - vars/vmware_vault.yml
    - vars/idm_vars.yml
    - vars/idm_vault.yml
    - vars/sat_vars.yml
    - vars/sat_vault.yml

  tasks:
    - name: "Test Task"
      ansible.builtin.include_tasks: tasks/inflate_image.yml
      tags:
        - buildimage
